on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Publish gem
      uses: dawidd6/action-publish-gem@v1
      with:
        #api_key: ${{secrets.RUBYGEMS_API_KEY}}
        github_token: ${{secrets.GITHUB_TOKEN}}
