on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Publish to Rubygems
      uses: cadwallion/publish-rubygems-action@v1.0.0
      env:
        RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        RELEASE_COMMAND: rake release
